### ISSUE TITLE
Host keys should be preserved accross container re-build

### ISSUE THREAD

**Issue by archont00** [grantbevis/borg-server#4]
Hi,

Thanks for the Dockerfile, it is usefull.

Would you mind modifying it so that the host keys are preserved?

I suggest something like:

```
cat /etc/ssh/sshd_config
...
HostKey /some/prefix/etc/ssh/...
HostKey /some/prefix/etc/ssh/...
...
```
and modifying the `service.sh`:
```
...
if [ ! -d /some/prefix/etc/ssh ]; then mkdir -p /some/prefix/etc/ssh; fi
ssh-keygen -A -f /some/prefix
...
```
and mounting the volume with `docker -v localdir_with_server_keys:/some/prefix/etc/ssh`.

**Comment by b3vis** [comment]
Sure I will also get this building via GitHub Actions to build the image and host it here on GHCR

**Comment by b3vis** [comment]
Hi @archont00, I have added the line `VOLUME /etc/ssh` to the Dockerfile which should hopefully keep your ssh hostkeys across rebuilds. Please let me know if this doesn't work. I have also introduced auto builds using GitHub Actions, you can get the latest image from here https://github.com/b3vis/borg-server/pkgs/container/borg-server

**Comment by archont00** [comment]
Hi,

I cannot test now, but: is it supposed to work with bind mounts?

The image will have `/etc/ssh/sshd_config`.

Once the container is created via `docker -v ./etc_ssh/:/etc/ssh borg ...`, where `./etc_ssh/` is an empty dir on host, wouldn't it wipe out (hide) the pre-existing `/etc/ssh/sshd_config` from the image? Or will it copy the sshd_config to the empty dir?

**Comment by callumgare** [comment]
I've just tried it out and I can confirm that sshd_config is copied into the volume mounted to /etc/ssh. Not sure what's doing the coping, I'm guessing `ssh-keygen -A`? The solution of setting the host keys dir to a different path is nice in that it allows you to mount a volume without needing to take over management of sshd_config (which is effectively what happens when you mount to /etc/ssh as you will no longer automatically receive updates to it when the image is updated). But other than that that downside things seem to work okay :)
